name: BattlePlugin
version: '${project.version}'
main: net.jcom.minecraft.battleplugin.BattlePlugin
api-version: '1.20'
load: STARTUP
commands:
  djbattle:
    usage: /<command>
    aliases: [ ]
    description: Battle Management-Command
    permission: battle-plugin.battle

  djteam:
    usage: /<command>
    aliases: [ ]
    description: Battle Team-Command
    permission: battle-plugin.team

permissions:
  battle-plugin.*:
    default: op
    description: OP-Permission for everything
    children:
      battle-plugin.battle.*: true

  battle-plugin.battle.*:
    default: op
    description: Battle-Management | Permission
    children:
      start: true
      stop: true
      reload: true
      init: true

  battle-plugin.battle.start:
    default: op
    description: Permission to start the battle | Permission

  battle-plugin.battle.stop:
    default: op
    description: Permission to stop the battle | Permission

  battle-plugin.battle.reload:
    default: op
    description: Permission to reload the config | Permission

  battle-plugin.battle.init:
    default: op
    description: Permission to initialize a battle world from config | Permission

  battle-plugin.team.*:
    default: true
    description: Battle-Team-Management | Permission
    children:
      join: true
      leave: true
      list: true

  battle-plugin.team.join:
    default: true
    description: Permission to join a team | Permission

  battle-plugin.team.leave:
    default: true
    description: Permission to leave a team | Permission

  battle-plugin.team.list:
    default: true
    description: Permission to list all teams | Permission