name: BattlePlugin
version: '${project.version}'
main: net.jcom.minecraft.battleplugin.BattlePlugin
api-version: '1.20'
load: STARTUP
commands:
  battle:
    usage: /<command>
    aliases: [ ]
    description: Battle-Command
    permission: battleplugin.battle

permissions:
  battleplugin.*:
    default: op
    description: OP-Permission for everything
    children:
      battleplugin.battle.*: true

  battleplugin.battle.*:
    default: op
    description: Battle-Management | Permission
    children:
      start: true
      stop: true
      reload: true
      init: true

  battleplugin.battle.start:
    default: op
    description: Permission to start the battle | Permission

  battleplugin.battle.stop:
    default: op
    description: Permission to stop the battle | Permission

  battleplugin.battle.reload:
    default: op
    description: Permission to reload the config | Permission

  battleplugin.battle.init:
    default: op
    description: Permission to initialize a battle world from config | Permission